apiVersion: v1
kind: Service
metadata:
  name: my-emp1
  labels:
    run: my-emp1
spec:
  type: LoadBalancer
  ports:
      - port: 80
        targetPort: 3000
        protocol: TCP
  selector:
      run: my-emp1

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-emp1
spec:
  replicas: 1
  selector:
      matchLabels:
          run: my-emp1
  template:
      metadata:
          labels:
              run: my-emp1
      spec:
          containers:
              - name: my-emp1
                image: adubois360/demo-node-mongo
                ports:
                  - containerPort: 3000
                env:
                  - name: MONGO_DEFAULT_HOSTNAME
                    value: "localhost"
              - name: mongo
                image: mongo
                ports:
                    - containerPort: 27017
